product-name: pivotal-mysql
product-properties:
  .properties.allow_lower_case_table_names_via_config_param:
    value: false
  .properties.audit_logging_enabled:
    value: false
  .properties.backups_selector:
    value: Azure Backups
  .properties.backups_selector.azure.account:
    value: ((backup_azure_account))
  .properties.backups_selector.azure.storage_access_key:
    value:
      secret: ((backup_azure_access_key))
  .properties.backups_selector.azure.path:
    value: ((backup_azure_path))
  .properties.backups_selector.azure.container:
    value: backups
  .properties.canary_instances:
    value: 0
  .properties.deprecated_bindings_string:
    value: X
  .properties.enable_lower_case_table_names:
    value: false
  .properties.enable_read_only_admin:
    value: false
  .properties.enable_secure_binding_credentials:
    value: true
  .properties.enable_tls_selector:
    value: disabled
  .properties.global_recipient_email:
    value: aneumann@pivotal.io
  .properties.global_service_instance_limit:
    value: 50
  .properties.local_infile:
    value: false
  .properties.mysql_metrics_frequency:
    value: 30
  .properties.plan1_selector:
    value: single_node
  .properties.plan1_selector.single_node.access_dropdown:
    value: enable
  .properties.plan1_selector.single_node.az_multi_select:
    value:
    - "null"
  .properties.plan1_selector.single_node.description:
    value: This plan provides a small dedicated MySQL instance.
  .properties.plan1_selector.single_node.name:
    value: db-small
  .properties.plan1_selector.single_node.paid_plan:
    value: false
  .properties.plan2_selector:
    value: single_node
  .properties.plan2_selector.single_node.access_dropdown:
    value: enable
  .properties.plan2_selector.single_node.az_multi_select:
    value:
    - "null"
  .properties.plan2_selector.single_node.description:
    value: This plan provides a medium dedicated MySQL instance.
  .properties.plan2_selector.single_node.name:
    value: db-medium
  .properties.plan2_selector.single_node.paid_plan:
    value: true
  .properties.plan3_selector:
    value: single_node
  .properties.plan3_selector.single_node.access_dropdown:
    value: enable
  .properties.plan3_selector.single_node.az_multi_select:
    value:
    - "null"
  .properties.plan3_selector.single_node.description:
    value: This plan provides a large dedicated MySQL instance.
  .properties.plan3_selector.single_node.name:
    value: db-large
  .properties.plan3_selector.single_node.paid_plan:
    value: true
  .properties.plan4_selector:
    value: Inactive
  .properties.plan5_selector:
    value: Inactive
  .properties.plan6_selector:
    value: Inactive
  .properties.plan7_selector:
    value: Inactive
  .properties.plan8_selector:
    value: Inactive
  .properties.plan9_selector:
    value: Inactive
  .properties.request_timeout:
    value: 120
  .properties.simultaneous_upgrades:
    value: 1
  .properties.syslog_migration_selector:
    value: disabled
  .properties.userstat:
    value: false
  .properties.wait_timeout:
    value: 28800
network-properties:
  network:
    name: pas
  other_availability_zones:
  - name: "null"
  service_network:
    name: services
  singleton_availability_zone:
    name: "null"
resource-config:
  dedicated-mysql-broker:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
errand-config:
  delete-all-service-instances-and-deregister-broker:
    pre-delete-state: true
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
  validate-before-upgrade-instances:
    post-deploy-state: true

