---
platform: linux
inputs:
- name: certs
params:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  CREDHUB_CA_CERT:
  NAME:
run:
  path: sh
  args:
  - -c
  - |
    cat /var/version && echo ""
    set -eux

    credhub login

    credhub set -n ${NAME} -t certificate -r "$(cat certs/chain.pem)" -c "$(cat certs/cert.pem)" -p "$(cat certs/privkey.pem)"