---
name: minio

releases:
- name: minio
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: minio
  azs: ((azs))
  instances: 1
  jobs:
  - name: minio-azure
    release: minio
    templates:
    - name: minio-azure
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      region: ((region))
      port: 9000
  networks:
  - name: ((network_name))
  vm_type: ((vm_type))
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1
