resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 2\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.pivnet_products))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.pivnet_products))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-image-(.*).tgz

- name: pas-stemcell
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3_secret_access_key))
    endpoint: ((s3.endpoint))
    bucket: ((s3.buckets.pivnet_products))
    regexp: pas-stemcell/bosh-stemcell-(.*).tgz

- name: pas-product
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3_secret_access_key))
    endpoint: ((s3.endpoint))
    bucket: ((s3.buckets.pivnet_products))
    regexp: cf-(.*).pivotal

- name: configuration
  type: git
  source:
    private_key: ((configuration_private_key.private_key))
    uri: ((configuration.uri))
    branch: ((configuration.branch))

- name: variable
  type: git
  source:
    private_key: ((configuration_private_key.private_key))
    uri: ((configuration.uri))
    branch: ((configuration.branch))

groups:
- name: fetch
  jobs:
  - fetch-platform-automation
  - fetch-pas
- name: install
  jobs:
  - install-opsman
  - upload-and-stage-pas
  - upload-pas-stemcell
  - install-pas
- name: delete
  jobs:
  - delete-foundation

jobs:
- name: fetch-platform-automation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - aggregate:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: fetch-pas
  plan:
  - aggregate:
    # - get: daily
    #   trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
    - get: variable
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
      PREFIX: '/foundations/nonprod'
      INTERPOLATION_PATH: "nonprod/product-configs"
    input_mapping:
      files: variable
    output_mapping:
      interpolated-files: variable
  - task: download-pas-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: nonprod/product-configs/pas.yml
    input_mapping:
      config: variable
    output_mapping:
      downloaded-stemcell: pas-stemcell
  - aggregate:
    - put: pas-product
      params:
        file: downloaded-product/*.pivotal
    - put: pas-stemcell
      params:
        file: pas-stemcell/*.tgz

- name: install-opsman
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml
      attempts: 10
      input_mapping:
        env: variable
        config: variable
      params:
        ENV_FILE: nonprod/vars/env.yml
        AUTH_CONFIG_FILE: nonprod/vars/auth.yml
    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml
      input_mapping:
        config: configuration
        env: variable
        vars: variable
      params:
        VARS_FILES: vars/nonprod/vars/director-vars.yml
        ENV_FILE: nonprod/vars/env.yml
        DIRECTOR_CONFIG_FILE: nonprod/config/director.yml
    - task: apply-director-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-director-changes.yml
      input_mapping:
        env: variable
      params:
        ENV_FILE: nonprod/vars/env.yml

- name: upload-and-stage-pas
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: variable
      - get: configuration
      - get: pas-product
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: upload-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-product.yml
      input_mapping:
        product: pas-product
        env: variable
      params:
        ENV_FILE: nonprod/vars/env.yml
    - task: stage-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/stage-product.yml
      params:
        ENV_FILE: nonprod/vars/env.yml
      input_mapping:
        product: pas-product
        env: variable

- name: upload-pas-stemcell
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: pas-stemcell
        # trigger: true
      - get: configuration
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: upload-pas-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        env: variable
        stemcell: pas-stemcell
      params:
        ENV_FILE: nonprod/vars/env.yml

- name: install-pas
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
        # passed:
          # - upload-and-stage-pas
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: configure-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        CONFIG_FILE: nonprod/config/cf.yml
        VARS_FILES: vars/nonprod/vars/cf-vars.yml
        ENV_FILE: nonprod/vars/env.yml
      input_mapping:
        config: configuration
        env: variable
        vars: variable
    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml
      params:
        ENV_FILE: nonprod/vars/env.yml
      input_mapping:
        env: variable

- name: delete-foundation
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: delete-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-installation.yml
      input_mapping:
        env: variable
      params:
        ENV_FILE: nonprod/vars/env.yml