resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 2\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.pivnet_products))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.pivnet_products))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-image-(.*).tgz

- name: configuration
  type: git
  source:
    private_key: ((configuration_private_key))
    uri: ((configuration.uri))
    branch: ((configuration.branch))

- name: variable
  type: git
  source:
    private_key: ((configuration_private_key))
    uri: ((configuration.uri))
    branch: ((configuration.branch))

jobs:
- name: fetch-platform-automation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - aggregate:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: install-opsman
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml
      attempts: 10
      input_mapping:
        env: variable
        config: variable
      params:
        ENV_FILE: nonprod/vars/env.yml
        AUTH_CONFIG_FILE: nonprod/vars/auth.yml
    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml
      input_mapping:
        config: configuration
        env: variable
        vars: variable
      params:
        VARS_FILES: vars/nonprod/vars/director-vars.yml
        ENV_FILE: nonprod/vars/env.yml
        DIRECTOR_CONFIG_FILE: nonprod/config/director.yml
    - task: apply-director-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-director-changes.yml
      input_mapping:
        env: variable
      params:
        ENV_FILE: nonprod/vars/env.yml

- name: delete-foundation
  serial: true
  serial_groups: [ install ]
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
      - get: variable
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((credhub-ca-cert))
        PREFIX: '/foundations/nonprod'
        INTERPOLATION_PATH: "nonprod/vars"
      input_mapping:
        files: variable
      output_mapping:
        interpolated-files: variable
    - task: delete-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-installation.yml
      input_mapping:
        env: variable
      params:
        ENV_FILE: nonprod/vars/env.yml